[
  {
    id: 0,
    latin: "Aeschynanthus lobianus",
    family: "Gesneriaceae",
    common: "Lipstick",
    category: "Hanging",
    origin: "Java",
    climate: "Tropical",
    tempmax: 89.6,
    tempmin: 57.2,
    ideallight: "Bright light",
    toleratedlight: "Direct sunlight",
    watering: "less frequent",
    image:
      "https://foliadesign.ca/cdn/shop/products/DSC_9573_2048x.jpg?v=1663603416",
    insects: ["Mealy bug", "Aphid", "Thrips"],
  },
  {
    id: 47,
    latin: "Cissus rhombifolia",
    family: "Vitaceae",
    common: "Ellen Danica",
    category: "Hanging",
    origin: "Cultivar",
    climate: "Subtropical",
    tempmax: 82.4,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "less frequent",
    image:
      "https://cb.scene7.com/is/image/Crate/TrailingFicusHangingPlantSSS21/$web_pdp_main_carousel_med$/201019091947/faux-trailing-ficus-hanging-plant-in-pot.jpg",
    insects: "Mealy bug",
    diseases: ["Downy mildiou", "Powdery"],
    use: ["Hanging", "Ground cover"],
  },
  {
    id: 56,
    latin: "Cissus rhombifolia",
    family: "Vitaceae",
    common: "Grape Ivy",
    category: "Hanging",
    origin: "Central America & South America",
    climate: "Tropical",
    tempmax: 82.4,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "less frequent",
    image:
      "https://m.media-amazon.com/images/I/61Bn0LBgFML.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    insects: "Mealy bug",
    diseases: ["Downy mildiou", "Powdery"],
    use: ["Hanging", "Ground cover"],
  },
  {
    id: 63,
    latin: "Chlorophytum comosum",
    family: "Liliaceae",
    common: "Spider plant",
    category: "Hanging",
    origin: "Central Africa",
    climate: "Tropical to subtropical",
    tempmax: 82.4,
    tempmin: 41,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "frequent",
    image: "https://m.media-amazon.com/images/I/51wtlZUB5ML._AC_.jpg",
    insects: "N/A",
    diseases: "N/A",
    use: ["Hanging", "Ground cover"],
  },
  {
    id: 93,
    latin: "Epipremnum aureum",
    family: "Araceae",
    common: "Marble Queen",
    category: "Hanging",
    origin: "Cultivar",
    climate: "Tropical",
    tempmax: 20,
    tempmin: 53.6,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "frequent",
    image:
      "https://img.kwcdn.com/product/Fancyalgo/VirtualModelMatting/ac9a58e59916e30b604ce7b7394d9a1b.jpg?imageView2/2/w/800/q/70",
    insects: "Mealy bug",
    diseases: ["Pythium"],
    use: ["Hanging", "Tertiary"],
  },
  {
    id: 103,
    latin: "Hedera canariensis",
    family: "Araliaceae",
    common: "Algerian ivy",
    category: "Hanging",
    origin: "Canaries",
    climate: "Subtropical",
    tempmax: 20,
    tempmin: 41,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "frequent",
    image:
      "https://dubaigardencentre.ae/getimage/products/hederahelix_i41323_prod_img_1_copy.jpg",
    insects: ["Spider mite", "Mealy bug", "Scale"],
    diseases: "N/A",
    use: ["Hanging", "Ground cover"],
  },
  {
    id: 104,
    latin: "Epipremnum aureum",
    family: "Araceae",
    common: "Golden Pothos",
    category: "Hanging",
    origin: "South Pacific",
    climate: "Tropical",
    tempmax: 20,
    tempmin: 53.6,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Average",
    image: "https://m.media-amazon.com/images/I/41IkfFhdJTL._AC_.jpg",
    insects: "Mealy bug",
    diseases: ["Pythium"],
    use: ["Hanging", "Tertiary"],
  },
  {
    id: 115,
    latin: "Hedera helix",
    family: "Araliaceae",
    common: "English ivy",
    category: "Hanging",
    origin: "Cultivar",
    climate: "Subtropical",
    tempmax: 20,
    tempmin: 41,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Average",
    image:
      "https://www.provenwinners.com/sites/provenwinners.com/files/imagecache/500x500/ifa_upload/hedera_glacier_mono.jpg",
    insects: ["Spider mite", "Mealy bug"],
    diseases: "N/A",
    use: ["Hanging", "Ground cover"],
  },
  {
    id: 1,
    latin: "Adiantum raddianum",
    family: "Polypodiaceae",
    common: "Maindenhair",
    category: "Fern",
    origin: "Brazil",
    climate: "Tropical",
    tempmax: 86,
    tempmin: 53.6,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Frequent",
    image:
      "https://botanically.nl/wp-content/uploads/2020/11/adiantum-capilius-veneris.jpg",
    insects: ["Mealy bug", "Aphid", "Snail"],
    diseases: "Gray mold",
    use: ["Potted plant", "Ground cover", "Table top"],
  },
  {
    id: 61,
    latin: "Asplenium nidus",
    family: "Aspleniaceae",
    common: "Birdnest fern",
    category: "Fern",
    origin: "Asia",
    climate: "Tropical humid",
    tempmax: 82.4,
    tempmin: 59,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Frequent",
    image: "https://m.media-amazon.com/images/I/81fqLV0QulL._AC_SL1500_.jpg",
    insects: "Mealy bug",
    diseases: "N/A",
    use: ["Potted plant", "Primary"],
  },
  {
    id: 64,
    latin: "Didymochlaena truncatula",
    family: "Dryopteridaceae",
    common: "Tree Maindenhair fern",
    category: "Fern",
    origin: "South America",
    climate: "Tropical humid",
    tempmax: 20,
    tempmin: 41,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Diffused",
    watering: "Frequent",
    image:
      "https://dartfrogconnection.com/media/catalog/product/cache/cfa8c0fc552e61495db3610f5747c90a/d/i/didymochlaena_truncatula_0154_2nd.jpg",
    insects: ["Mealy bug", "Scale"],
    diseases: "N/A",
    use: ["Potted plant", "Tertiary"],
  },
  {
    id: 79,
    latin: "Cyrtomium falcatum",
    family: "Dryopteridaceae",
    common: "Holly-fern",
    category: "Fern",
    origin: "Asia",
    climate: "Subtropical",
    tempmax: 20,
    tempmin: 41,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Average",
    image:
      "https://www.plantvine.com/plants/Cyrtomium-falcatum-large-holly-fern-copy.jpg",
    insects: ["Scale", "Mealy bug"],
    diseases: "N/A",
    use: ["Potted plant", "Ground cover"],
  },
  {
    id: 124,
    latin: "Pellaea falcata",
    family: "Sinopteridaceae",
    common: "sickle fern",
    category: "Fern",
    origin: "Australia & New Guinea",
    climate: "Tropical",
    tempmax: 77,
    tempmin: 53.6,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Frequent",
    image:
      "https://i.etsystatic.com/11587994/r/il/80650d/978886120/il_fullxfull.978886120_q8p1.jpg",
    insects: "Mealy bug",
    diseases: "N/A",
    use: ["Table top", "Ground cover", "Tertiary"],
  },
  {
    id: 152,
    latin: "Pteris cretica Parkeri",
    family: "Pteridaceae",
    common: "Cretan brake",
    category: "Fern",
    origin: "Cultivar",
    climate: "Tropical humid",
    tempmax: 82.4,
    tempmin: 53.6,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Frequent",
    image:
      "https://www.tropicopia.com/house-plant/originals/Pteris%20cretica%20Parkeri%2006.jpg",
    insects: "N/A",
    diseases: "N/A",
    use: ["Table top", "Tertiary"],
  },
  {
    id: 28,
    latin: "Allamanda nerifolia",
    family: "Apocynaceae",
    common: "Golden Trumpet",
    category: "Flower",
    origin: "Brazil",
    climate: "Tropical",
    tempmax: 20,
    tempmin: 50,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "Average",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Flowers_of_Allamanda_cathartica_in_West_Bengal%2C_India.jpg/1024px-Flowers_of_Allamanda_cathartica_in_West_Bengal%2C_India.jpg",
    insects: ["Mealy bug", "Scale", "Spider mite"],
    diseases: "N/A",
    use: "Flower",
  },
  {
    id: 42,
    latin: "Bougainvillea",
    family: "Nyctaginaceae",
    common: "Paper flower",
    category: "Flower",
    origin: "Cultivar",
    climate: "Tropical",
    tempmax: 89.6,
    tempmin: 50,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "Average",
    image:
      "https://assets.wfcdn.com/im/70873102/resize-h445%5Ecompr-r85/2479/247940644/Bougainvillea+Hanging+Basket+Arrangement+in+Basket.jpg",
    insects: ["Aphid", "Mealy bug"],
    diseases: "N/A",
    use: ["Potted plant", "Colors / Forms", "Primary"],
  },
  {
    id: 119,
    latin: "Mandevilla X",
    family: "Apocynaceae",
    common: "Dipladenia",
    category: "Flower",
    origin: "Hybrid",
    climate: "Tropical",
    tempmax: 20,
    tempmin: 50,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "Frequent",
    image:
      "https://creativeplantdesigns.com/wp-content/uploads/2015/09/MandevillaTrellis10.jpg",
    insects: ["Spider mite", "Mealy bug", "Aphid"],
    diseases: "N/A",
    use: ["Flower", "Potted plant"],
  },
  {
    id: 122,
    latin: "Hedychium coronarium",
    family: "Zingiberaceae",
    common: "White Ginger",
    category: "Flower",
    origin: "China",
    climate: "Subtropical",
    tempmax: 20,
    tempmin: 50,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "Frequent",
    image:
      "https://assets.wfcdn.com/im/02060305/resize-h445%5Ecompr-r85/8834/88341230/12%22+Potted+Hedychium+Coronarium+Spring+Artificial+Floral+Arrangement.jpg",
    insects: "N/A",
    diseases: "N/A",
    use: ["Flower", "Secondary"],
  },
  {
    id: 138,
    latin: "Phalaenopsis X",
    family: "Orchidaceae",
    common: "phalaenopsis orchid",
    category: "Flower",
    origin: "Hybrid",
    climate: "Tropical humid",
    tempmax: 82.4,
    tempmin: 53.6,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "less frequent",
    image:
      "https://assets.wfcdn.com/im/20974951/resize-h445%5Ecompr-r85/2414/241404008/Handmade+Phalaenopsis+Silk+Orchid+Floral+Arrangement+in+Pot.jpg",
    insects: ["Thrips", "Aphid"],
    diseases: "N/A",
    use: ["Table top", "Secondary"],
  },
  {
    id: 35,
    latin: "Caryota mitis",
    family: "Palmae",
    common: "Fish tail palm",
    category: "Palm",
    origin: " India",
    climate: "Tropical",
    tempmax: 77,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Frequent",
    image:
      "https://cb.scene7.com/is/image/Crate/PottedFishTailPalmSSS23/$web_pdp_main_carousel_med$/221111145008/potted-faux-fishtail-palm-tree-6.5.jpg",
    insects: ["Spider mite", "Mealy bug"],
    diseases: "N/A",
    use: ["Potted plant", "Primary"],
  },
  {
    id: 39,
    latin: "Chamaedorea elegans",
    family: "Arecaceae",
    common: "Bella palm",
    category: "Palm",
    origin: "Mexico",
    climate: "Tropical",
    tempmax: 82.4,
    tempmin: 41,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Average",
    image:
      "https://www.ikea.com/us/en/images/products/chamaedorea-elegans-potted-plant-parlor-palm__0121094_pe277873_s5.jpg?f=xs",
    insects: ["Spider mite", "Mealy bug", "Scale"],
    diseases: "N/A",
    use: ["Potted plant", "Tertiary"],
  },
  {
    id: 43,
    latin: "Chamaedorea seifrizii",
    family: "Arecaceae",
    common: "Reed Palm",
    category: "Palm",
    origin: "Mexico",
    climate: "Tropical",
    tempmax: 20,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Average",
    image: "https://m.media-amazon.com/images/I/91aqkyr0jjL._AC_SL1500_.jpg",
    insects: ["Spider mite", "Mealy bug"],
    diseases: "N/A",
    use: ["Potted plant", "Secondary"],
  },
  {
    id: 49,
    latin: "Chamaedorea erumpens",
    family: "Arecaceae",
    common: "Bamboo palm",
    category: "Palm",
    origin: "Honduras",
    climate: "Tropical",
    tempmax: 82.4,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Average",
    image: "https://www.plantscape.com/Images/PSG-2016/bamboopalm14.jpg",
    insects: ["Spider mite", "Mealy bug"],
    diseases: "N/A",
    use: ["Potted plant", "Secondary"],
  },
  {
    id: 58,
    latin: "Chamaedorea metallica",
    family: "Arecaceae",
    common: "Miniature fishtail",
    category: "Palm",
    origin: "Mexico",
    climate: "Tropical",
    tempmax: 20,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Average",
    image:
      "https://static.wixstatic.com/media/0906d2_9e8b8c7c8e1a452895d19fe457e07a39~mv2.webp",
    insects: "Mealy bug",
    diseases: "N/A",
    use: ["Potted plant", "Secondary"],
  },
  {
    id: 74,
    latin: "Cycas revoluta",
    family: "Cycadaceae",
    common: "Sago palm",
    category: "Palm",
    origin: "Japan",
    climate: "Subtropical",
    tempmax: 20,
    tempmin: 46.4,
    ideallight: "Prefers bright, indirect sunlight.",
    toleratedlight: "Partial shade",
    watering: "less frequent",
    image:
      "https://cdn.webshopapp.com/shops/30495/files/416531287/cycas-cycas-revoluta-king-sago-palm.jpg",
    insects: ["Scale", "Mealy bug"],
    diseases: "N/A",
    use: ["Potted plant", "Primary"],
  },
  {
    id: 89,
    latin: "Dypsis lutescens",
    family: "Arecaceae",
    common: "Butterfly palm",
    category: "Palm",
    origin: "Madagascar",
    climate: "Tropical",
    tempmax: 82.4,
    tempmin: 50,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "Frequent",
    image:
      "https://www.brighterblooms.com/cdn/shop/products/Areca_Palm_2_BB.jpg?v=1638144873&width=650",
    insects: ["Spider mite", "Mealy bug", "Scale"],
    diseases: "N/A",
    use: ["Potted plant", "Secondary"],
  },
  {
    id: 128,
    latin: "Pachypodium geayi",
    family: "Apocynaceae",
    common: "Madagascar Palm",
    category: "Cactus And Succulent",
    origin: "Madagascar",
    climate: "Arid Tropical",
    tempmax: 95,
    tempmin: 46.4,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "infrequent",
    image: "https://mygardenlife.com/wp-content/uploads/2022/12/6882_9-2.jpg",
    insects: "Mealy bug",
    diseases: "N/A",
    use: ["Potted plant", "Primary"],
  },
  {
    id: 2,
    latin: "Aechmea fatsiata",
    family: "Bromeliaceae",
    common: "Silver vase",
    category: "Bromeliad",
    origin: "Brazil",
    climate: "Tropical humid",
    tempmax: 20,
    tempmin: 53.6,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "less frequent",
    image:
      "https://i0.wp.com/laidbackgardener.blog/wp-content/uploads/2016/01/20160111a.jpg?w=380&ssl=1",
    insects: "N/A",
    diseases: "N/A",
    use: ["Flower", "Table top", "Tertiary"],
  },
  {
    id: 70,
    latin: "Cryptanthus Rose Elaine",
    family: "Bromeliaceae",
    common: "Earth Star",
    category: "Bromeliad",
    origin: "Cultivar",
    climate: "Tropical",
    tempmax: 82.4,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Direct sunlight",
    watering: "Average",
    image:
      "https://www.tropicopia.com/house-plant/originals/Cryptanthus%20Rose%20Eliane%2004.jpg",
    insects: "N/A",
    diseases: "N/A",
    use: ["Table top", "Primary"],
  },
  {
    id: 94,
    latin: "Guzmania",
    family: "Bromeliaceae",
    common: "Guzmania Sunnytime",
    category: "Bromeliad",
    origin: "Cultivar",
    climate: "Tropical",
    tempmax: 20,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "less frequent",
    image:
      "https://olivehill.net/wp-content/uploads/2018/10/06GuzmaniaGeorgia-800x800.jpg",
    insects: "N/A",
    diseases: "N/A",
    use: ["Table top", "Tertiary"],
  },
  {
    id: 96,
    latin: "Guzmania",
    family: "Bromeliaceae",
    common: "Guzmania Empire",
    category: "Bromeliad",
    origin: "Cultivar",
    climate: "Tropical",
    tempmax: 20,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "less frequent",
    image:
      "https://succulentsbox.com/cdn/shop/files/29_a9e47b3f-d97f-40cf-843d-60cb6218cabe_2000x.jpg?v=1697013909",
    insects: "N/A",
    diseases: "N/A",
    use: ["Table top", "Tertiary"],
  },
  {
    id: 101,
    latin: "Guzmania",
    family: "Bromeliaceae",
    common: "Claret",
    category: "Bromeliad",
    origin: "Cultivar",
    climate: "Tropical",
    tempmax: 20,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "less frequent",
    image:
      "https://cdn.shopify.com/s/files/1/0068/4215/5090/t/115/assets/4b7badba6c9b--PL-BromeliadCLaire-6IN-po-lr-gray_730x.jpg?v=1633120877",
    insects: "N/A",
    diseases: "N/A",
    use: ["Table top", "Tertiary"],
  },
  {
    id: 108,
    latin: "Guzmania",
    family: "Bromeliaceae",
    common: "Mariposa",
    category: "Bromeliad",
    origin: "Cultivar",
    climate: "Tropical",
    tempmax: 20,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "less frequent",
    image:
      "https://endanea.com/wp-content/uploads/2021/01/guzmania-planta-con-flor-570x718.jpg",
    insects: "N/A",
    diseases: "N/A",
    use: ["Table top", "Tertiary"],
  },
  {
    id: 110,
    latin: "Guzmania",
    family: "Bromeliaceae",
    common: "Marjan",
    category: "Bromeliad",
    origin: "Cultivar",
    climate: "Tropical",
    tempmax: 20,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "less frequent",
    image:
      "https://westbrae-nursery.com/cdn/shop/products/GuzmaniaMarjan6in_900x.jpg?v=1582260214",
    insects: "N/A",
    diseases: "N/A",
    use: ["Table top", "Tertiary"],
  },
  {
    id: 112,
    latin: "Guzmania",
    family: "Bromeliaceae",
    common: "Rana",
    category: "Bromeliad",
    origin: "Cultivar",
    climate: "Tropical",
    tempmax: 20,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "less frequent",
    image:
      "https://olivehill.net/wp-content/uploads/2015/08/08GuzmaniaLisa3ppp6-1-800x800.jpg",
    insects: "N/A",
    diseases: "N/A",
    use: ["Table top", "Tertiary"],
  },
  {
    id: 114,
    latin: "Euphorbia drupifera",
    family: "Euphorbiaceae",
    common: "spurge",
    category: "Cactus And Succulent",
    origin: "Guinea",
    climate: "Arid Tropical",
    tempmax: 95,
    tempmin: 53.6,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "infrequent",
    image:
      "https://www.sunshinetropical.com/wp-content/uploads/2018/07/14-EUP-DRUP-GREEN-GIANT.jpg",
    insects: "Mealy bug",
    diseases: "Downy mildiou",
    use: ["Potted plant", "Primary"],
  },
  {
    id: 128,
    latin: "Pachypodium geayi",
    family: "Apocynaceae",
    common: "Madagascar Palm",
    category: "Cactus And Succulent",
    origin: "Madagascar",
    climate: "Arid Tropical",
    tempmax: 95,
    tempmin: 46.4,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "infrequent",
    image: "https://mygardenlife.com/wp-content/uploads/2022/12/6882_9-2.jpg",
    insects: "Mealy bug",
    diseases: "N/A",
    use: ["Potted plant", "Primary"],
  },
  {
    id: 3,
    latin: "Agave angustilolia Marginata",
    family: "Amaryllidaceae",
    common: "Century plant",
    category: "Cactus And Succulent",
    origin: " India",
    climate: "Tropical",
    tempmax: 95,
    tempmin: 41,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "infrequent",
    image:
      "https://assets.wfcdn.com/im/75588655/resize-h445%5Ecompr-r85/2443/244329906/Christie+27%27%27+Faux+Agave+Plant+in+Pot.jpg",
    insects: ["Scale", "Mealy bug"],
    diseases: "N/A",
    use: ["Potted plant", "Primary", "Secondary"],
  },
  {
    id: 6,
    latin: "Agave filifera",
    family: "Amaryllidaceae",
    common: "Thread Agave",
    category: "Cactus And Succulent",
    origin: "Mexico",
    climate: "Arid Tropical",
    tempmax: 95,
    tempmin: 41,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "infrequent",
    image:
      "https://littleprinceplants.com/wp-content/uploads/2020/01/Agave-Royal-Flush-scaled.jpg.webp",
    insects: ["Scale", "Mealy bug"],
    diseases: "N/A",
    use: ["Potted plant", "Primary", "Secondary"],
  },
  {
    id: 8,
    latin: "Agave attenuata",
    family: "Amaryllidaceae",
    common: "Dragon tree Agave",
    category: "Cactus And Succulent",
    origin: "Mexico",
    climate: "Arid Tropical",
    tempmax: 95,
    tempmin: 41,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "infrequent",
    image:
      "https://images.squarespace-cdn.com/content/v1/5968af67414fb590cb8f77e3/1562315482549-2UA9IUI99VLE28OCSWNV/81HW-rmnO1L._SL1500_.jpg?format=1500w",
    insects: ["Scale", "Mealy bug"],
    diseases: "N/A",
    use: ["Potted plant", "Primary", "Secondary"],
  },
  {
    id: 19,
    latin: "Agave verschaffeltii",
    family: "Amaryllidaceae",
    common: "Blue Agave",
    category: "Cactus And Succulent",
    origin: "Mexico",
    climate: "Arid Tropical",
    tempmax: 95,
    tempmin: 53.6,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "infrequent",
    image:
      "https://d2j6dbq0eux0bg.cloudfront.net/images/9347649/3374012011.jpg",
    insects: ["Scale", "Mealy bug"],
    diseases: "N/A",
    use: ["Potted plant", "Primary", "Secondary"],
  },
  {
    id: 22,
    latin: "Agave striata",
    family: "Amaryllidaceae",
    common: "Lilliput Agave",
    category: "Cactus And Succulent",
    origin: "Mexico",
    climate: "Arid Tropical",
    tempmax: 95,
    tempmin: 53.6,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "infrequent",
    image:
      "https://www.seeds-gallery.com/8586-large_default/sporoi-agave-striata.jpg",
    insects: ["Scale", "Mealy bug"],
    diseases: "N/A",
    use: ["Potted plant", "Primary", "Secondary"],
  },
  {
    id: 37,
    latin: "Cereus peruvianus",
    family: "Cactaceae",
    common: "Tree Cereus",
    category: "Cactus And Succulent",
    origin: "Brazil",
    climate: "Arid Tropical",
    tempmax: 95,
    tempmin: 41,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "infrequent",
    image:
      "https://m.media-amazon.com/images/I/81vahJcrIUL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    insects: ["Scale", "Mealy bug"],
    diseases: "N/A",
    use: ["Potted plant", "Primary"],
  },
  {
    id: 34,
    latin: "Anthurium superbum",
    family: "Araceae",
    common: "Bronze Anthurium",
    category: "Anthurium",
    origin: "Ecuador",
    climate: "Tropical",
    tempmax: 82.4,
    tempmin: 64.4,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "less frequent",
    image:
      "https://shoptansy.com/cdn/shop/products/image_c5557f9d-94ee-4c73-9227-d66d048c60b2_720x.jpg?v=1631049471",
    insects: ["Spider mite", "Mealy bug"],
    diseases: "N/A",
    use: ["Table top", "Colors / Forms", "Secondary"],
  },
  {
    id: 45,
    latin: "Anthurium X",
    family: "Araceae",
    common: "Tailflower",
    category: "Anthurium",
    origin: "Cultivar",
    climate: "Tropical",
    tempmax: 71.6,
    tempmin: 64.4,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "less frequent",
    image:
      "https://cdn-folnc.nitrocdn.com/fmzeQfhBETiKkxuuwSMibDGzEKvFOImH/assets/images/optimized/rev-529a1dc/culturedplants.com/wp-content/uploads/2022/06/Anthurium-crystallinum-x-forgetii-2.jpg",
    insects: ["Spider mite", "Mealy bug", "Aphid"],
    diseases: ["Erwinia", "Crown rot"],
    use: ["Flower", "Table top", "Tertiary"],
  },
  {
    id: 46,
    latin: "Anthurium hookeri",
    family: "Araceae",
    common: "Bird nest Anthurium",
    category: "Anthurium",
    origin: "Guyana",
    climate: "Tropical humid",
    tempmax: 82.4,
    tempmin: 64.4,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "less frequent",
    image:
      "https://okanoka.com/cdn/shop/products/582814-wm-16915.5_watermarked_1024x1024@2x.jpg?v=1664713527",
    insects: ["Mealy bug", "Snail", "Aphid"],
    diseases: ["Erwinia", "Crown rot"],
    use: ["Potted plant", "Secondary"],
  },
  {
    id: 57,
    latin: "Anthurium schlechtendalii",
    family: "Araceae",
    common: "Cabbage Anthurium",
    category: "Anthurium",
    origin: "Costa rica",
    climate: "Tropical",
    tempmax: 82.4,
    tempmin: 64.4,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "less frequent",
    image:
      "https://www.thejunglecollective.com.au/wp-content/uploads/2020/05/Anthurium-Schlechtendalii-200mm-s.jpg.webp",
    insects: ["Spider mite", "Mealy bug", "Aphid"],
    diseases: "N/A",
    use: ["Potted plant", "Colors / Forms", "Primary"],
  },
  {
    id: 62,
    latin: "Anthurium hookeri",
    family: "Araceae",
    common: "Birds nest Anthurium",
    category: "Anthurium",
    origin: "Guyana",
    climate: "Tropical humid",
    tempmax: 82.4,
    tempmin: 64.4,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "less frequent",
    image:
      "https://i.etsystatic.com/23242079/r/il/8cada3/3737512943/il_794xN.3737512943_krx7.jpg",
    insects: ["Mealy bug", "Snail", "Aphid"],
    diseases: ["Erwinia", "Crown rot"],
    use: ["Potted plant", "Primary"],
  },
  {
    id: 41,
    latin: "Calathea pictura Argentea",
    family: "Marantaceae",
    common: "Silver Calathea",
    category: "Foliage plant",
    origin: "Cultivar",
    climate: "Tropical",
    tempmax: 77,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Average",
    image: "https://m.media-amazon.com/images/I/81RzBbD-i3L._AC_SX679_.jpg",
    insects: ["Spider mite", "Mealy bug", "Scale"],
    diseases: "N/A",
    use: ["Table top", "Ground cover", "Tertiary"],
  },
  {
    id: 36,
    latin: "Codiaeum petra",
    family: "Euphorbiaceae",
    common: "Croton",
    category: "Foliage plant",
    origin: "Cultivar",
    climate: "Tropical",
    tempmax: 82.4,
    tempmin: 50,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "Average",
    image:
      "https://nurserynisarga.in/wp-content/uploads/2023/02/Buy-Croton-Petra-Plant-Online.webp",
    insects: ["Spider mite", "Mealy bug"],
    diseases: "N/A",
    use: ["Potted plant", "Secondary"],
  },
  {
    id: 40,
    latin: "Calathea veitchiana",
    family: "Marantaceae",
    common: "Medallion Calathea",
    category: "Foliage plant",
    origin: "Hybrid",
    climate: "Tropical",
    tempmax: 77,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Average",
    image:
      "https://www.lightbulbs.com/catalog/product_photos/Vickerman/724460md.jpg",
    insects: ["Spider mite", "Mealy bug", "Scale"],
    diseases: "N/A",
    use: ["Table top", "Ground cover"],
  },
  {
    id: 50,
    latin: "Calathea stromata",
    family: "Marantaceae",
    common: "Stromante",
    category: "Foliage plant",
    origin: "Brazil",
    climate: "Tropical",
    tempmax: 77,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Average",
    image:
      "https://plantworldlondon.com/wp-content/uploads/2021/06/Calathea-Ornata-Sanderiana-1.jpg",
    insects: ["Spider mite", "Mealy bug", "Scale"],
    diseases: "N/A",
    use: ["Table top", "Ground cover"],
  },
  {
    id: 51,
    latin: "Codiaeum",
    family: "Euphorbiaceae",
    common: "Garden Croton",
    category: "Foliage plant",
    origin: "Cultivar",
    climate: "Tropical",
    tempmax: 82.4,
    tempmin: 50,
    ideallight: "6 or more hours of direct sunlight per day.",
    toleratedlight: "Direct sunlight.",
    watering: "Average",
    image:
      "https://shopyarrow.com/cdn/shop/products/Yarrow.Shop_Houseplant_Plant_-74_860x.jpg?v=1607985340",
    insects: ["Spider mite", "Mealy bug"],
    diseases: "N/A",
    use: ["Secondary", "Tertiary"],
  },
  {
    id: 60,
    latin: "Calathea ornata Rosea lineata",
    family: "Marantaceae",
    common: "Stiped calathea",
    category: "Foliage plant",
    origin: "Cultivar",
    climate: "Tropical",
    tempmax: 77,
    tempmin: 50,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Average",
    insects: ["Spider mite", "Mealy bug", "Scale"],
    diseases: "N/A",
    use: ["Table top", "Ground cover", "Tertiary"],
  },
  {
    id: 76,
    latin: "Ctenanthe lubbersiana",
    family: "Marantaceae",
    common: "Phrynium",
    category: "Foliage plant",
    origin: "Brazil",
    climate: "Tropical",
    tempmax: 77,
    tempmin: 53.6,
    ideallight: "Bright light",
    toleratedlight: "Diffused",
    watering: "Frequent",
    image:
      "https://i0.wp.com/www.halaplants.ae/wp-content/uploads/2021/04/Ctenanthe-lubbersiana-19L.jpg?fit=800%2C800&ssl=1",
    insects: ["Spider mite", "Mealy bug"],
    diseases: "N/A",
    use: ["Potted plant", "Secondary"],
  },
  {
    id: 132,
    latin: "Liriope muscari Variegata",
    family: "Liliaceae",
    common: "Variegated lily turf",
    category: "Foliage plant",
    origin: "Japan",
    climate: "Subtropical",
    tempmax: 20,
    tempmin: 46.4,
    ideallight: "Bright light",
    toleratedlight: "Direct sunlight",
    watering: "Average",
    image: "https://treemart.org/wp-content/uploads/2023/03/Liriope.-asst.webp",
    insects: ["Spider mite", "Scale"],
    diseases: "N/A",
    use: ["Ground cover", "Table top"],
  },
];
